name: StoryJam
favicon: null
layout_spectrum: 0.3989607240073383
typography_spectrum: 0.13802655460312963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07299283216707408
  lightness: 0.6529724604915828
  saturation: 0.7294676476158202
  rhythmicContrast: 0.6351604277733713
purpose: []
